version: '3.8'

services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
      - MLFLOW_TRACKING_URI=file:./mlruns
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MLflow tracking server
  mlflow-server:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    working_dir: /mlruns
    command: >
      sh -c "pip install mlflow && 
             mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns"
    restart: unless-stopped
    depends_on:
      - credit-risk-api

networks:
  default:
    name: credit-risk-network