name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8 mypy

    - name: Run static analysis
      run: |
        black --check src/ tests/
        flake8 src/ tests/
        mypy src/

    - name: Run tests with pytest
      run: |
        pytest --cov=src --cov-report=xml tests/
      env:
        PYTHONPATH: ${{ github.workspace }}/src

    - name: Upload coverage
      uses: codecov/codecov-action@v3

#   docker:
#     name: Docker Build & Test
#     runs-on: ubuntu-latest
#     needs: test  # Depends on test job succeeding first
    
#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

 